### ISSUE TITLE
In dark mode the processed items are invisible (white on white I think)

### ISSUE THREAD

**Issue by jehrler** [stant/mdcsvimporter2015#10]
In dark mode the processed items are invisible (white on white I think)

<img width="791" alt="Screen Shot 2019-07-02 at 9 16 01 AM" src="https://user-images.githubusercontent.com/52459114/60520129-7999b280-9caa-11e9-8a78-cbb3a0514a4f.png">

**Comment by stant** [comment]
hmmm. Ok. I don't have time to look right now, but I did no programming to work with Dark Mode. It looks like Mac is reversing colors itself and I do not know why it is not reversing to table also. 
If you select a number of cells does the highlighting make anything show up?

**Comment by jehrler** [comment]
Thanks for the suggestion.  When i click (not click and drag, just click) everything from that point down becomes visible.
<img width="778" alt="Screen Shot 2019-07-08 at 12 23 23 PM" src="https://user-images.githubusercontent.com/52459114/60829834-78212c00-a17b-11e9-9f2e-913bd33d0a49.png">

If I click on the header where it says date, the whole thing becomes visible.
<img width="781" alt="Screen Shot 2019-07-08 at 12 23 49 PM" src="https://user-images.githubusercontent.com/52459114/60829851-896a3880-a17b-11e9-8593-6a0e473ebc12.png">

**Comment by stant** [comment]
well, what version of Java are you using? If 8, try the newest version of 8.

**Comment by jehrler** [comment]
java 8, update 211.

Now that I know I can just click to view all the info I am ok, just an fyi in case others have the issue now that dark mode is becoming more of a thing on ios and macos

**Comment by stant** [comment]
yeah. I don't know whose problem that is, but glad you have an easy work-around.
