### ISSUE TITLE
CSV Importer crashes in md 2022.3(4072)

### ISSUE THREAD

**Issue by yogi1967** [stant/mdcsvimporter2015#12]
FeatureModule has been recently changed to make most of its methods final, including .getBuild() and .getDescription(). 

Your extension extends FeatureModule and overrides these methods. Hence the extension now crashes. 

You shouldn’t need these methods anyway as the data comes from meta_info.dict. Perhaps a quick fix would be to remove these overrides?

thanks.

**Comment by stant** [comment]
it looks like this same day I created a new build to fix this:
quick update to work with MD2022
https://github.com/stant/mdcsvimporter2015/releases/tag/v23
