### ISSUE TITLE
Missing functionalities

### ISSUE THREAD

**Issue by ghost** [stant/mdcsvimporter2015#2]
In my old, "ancient" mdcsvimporter, issued by Milutan Jovanovic, special for me importing a ING csv file in the Netherlands, I had the following functionalities, now missing in the new one. Don't misunderstand me, I am very grateful that somebody made an effort, but it's a pity anyhow.
Missing functionalities are:
1. import the same file twice. My own responsibility,,
2. show the latest transaction with the same "Description",
3. compare new transactions with existing ones register and merge them, when requested..
Attached would be the latest (IBAN) version of a ING download file, if a csv file would be allowed. 
Thanks

**Comment by stant** [comment]
for 1.)  You can import the same file twice or more. It just does not add duplicate transactions. This was a big enhancement. Now you can import csv files with overlapping dates/transactions and not have to worry about getting duplicate transactions!

Are you saying you want it to add dup transactions?  I could put a checkbox to allow this if a number of people want this possibility. If people want to comment on that here, I would consider it. Why would you want to do that so I understand?

**Comment by stant** [comment]
for 2. and 3.) Are those only when you import duplicates? If so, I would have to allow that. mdcsvimporter showed no comparison screen itself ever that I know of.
Once the import happens, that is MD functionality and you would have to talk to MD.
If you can paste a screenshot to explain what you mean, please do. It looks like you can drop images into these comments.

**Comment by ghost** [comment]
for 2. and 3.) sometimes I enter transactions "by hand" in a register. When a download follows, a check whether the Description and amount is present already, would be handy. Was in the old version.
for 1.) Sometimes I mess up a downloaded transaction and I should be able to reproduce it again, without downloading from the bank again. When I don't want this to be available, I can always check the "Delete file" button.

**Comment by stant** [comment]
I don't understand why you cannot still add a manual transaction. I would think you can. That is part of MD so you need to ask them.

For 2. 3. You almost sound like you want the importer to find a duplicate between your manual add and a downloaded import or no?

For 1. I don't understand what you mean. You do have the option of having the importer auto delete the downloaded csv file or not.

**Comment by ghost** [comment]
I think we misunderstand each other.
My procedure with the former mdcsvimporter was like this:
I usually enter transactions manual when they happen.
About once a week I downloaded a csv-file and imported that file into the register (just as a double check that none were forgotten).
After the import the “blue button” showed and I went to the register where imported and manual transactions were shown.
Pressing the cursor on an imported transaction resulted in a box where other transactions, including the manual transaction, were shown.
Clicking that specific manual transaction resulted in a merge with the imported one (or the other way around) leaving the date, split, description of the manual transaction in tact.
Now I don’t know what part was done by MD or by mdcsvimporter, but with the new importer only transactions with the same “Description” are shown,
however not the manual transaction. Clicking on one of those, it only picks up the Description-field. 
The manual entered transaction is stil there, unchanged, So that leaves two of the same transactions. 
Maybe my new procedure will have to be, not to enter transactions manual anymore.

On the issue of importing the same csv-file twice:
Yes, there is an option of deleting the file after import or not, but if I choose NOT to delete the file, I should be able to import it again.
What else is the use of on purpose leaving the file there?

**Comment by stant** [comment]
![manual](https://cloud.githubusercontent.com/assets/1928413/6597559/f9e1c5aa-c7d3-11e4-8c4b-6084b31e6d8b.JPG)
![downloaded-compare](https://cloud.githubusercontent.com/assets/1928413/6597562/fe16213e-c7d3-11e4-895d-b43ff4cfac61.JPG)

1.) yes, you can import the same file more than once. my importer skips duplicates though as I want it to.  I think that is not an issue. The checkbox works too.

2.) I just tried md2014 and md2015. If I add a manual trans. in either, it does not show the 'blue ball' for that trans. That is a function of md because the importer is not involved. And, yes, it therefore does not offer to compare the trans to others to merge or 'confirm'. You can talk to MD. Are you coming from an older version of md?

3.) the 'blue ball' might be a feature that I am setting in my importer that I think I saw the md csv importer does not do. So my imports do turn on the blue ball. How that works after that in MD is a question for them.

4.) Personally, when I used to use Quicken, that never came for os/2 or linux, and I switched to MD, I also changed my accounting methods. I quit entering transes manually myself and I just download them into MD. Now I can download overlappying dates and files and all is well. I just look over what I download and 'confirm' transes. It saves typing and I think it is faster.

I think we can probably close this issue?
If you have other questions, let me know.
Thanks,
Stan

**Comment by ghost** [comment]
1.) In my experience one can not import the same file twice. Tried it again and no records imported. Could be that one has to delete existing, similar records first.

Which brings me to the following: I perceived before that an existing record could not even be processed. Now, with a fresh download I noticed, that although the file reader is visible, I called it "ING import”, there is always a remark: “find reader”. I would prefer that if you have 1 reader the importer would automatically use that reader. Or if you have more than 1, the importer would use the last one used or shown. To activate the “Process", one has to click on “Find All Readers” first. “find reader” is still shown then, but at least, the Process-button is activated and can be used. 
Remark: Before I noticed this mechanism, it could be that I thought the file could not be imported twice! (see 1.) 
BTW: When I click on “Find Import File(s) for this reader, when a file is already selected, I get the message “Unsupported CSV file format.”, which is a misleading remark.

2.) On the “blue ball” issue, for me it’s difficult to know where the importer ends and MD starts.
I used the special (Jovanovic made) importer in MD 2014 (always used the latest (preview) build), which showed a small "blue ball” on the sidebar behind the registername (MD?).
Going to the register, the larger “blue ball” was shown for each transaction.
Clicking on a “blue ball” transaction showed a box with old transactions for the same Description, but always shown first was the similar and latest transaction (Description, Amount) already in the register. Could be the sort, latest first. Clicking on that transaction made the imported and that transaction merge, as explained before.
If that mechanism was Moneydance, then I’ll approach them.
1. With this mornings import I noticed that a credit was on the debit side. Should I pick up a sign somewhere?

You can close this issue or make separate issues of my new findings.

If you don’t want to have new findings reported, say so. I seem to be the only one with findings. Are there no other users for this Extension or have others no problem with it?

Thanks for your patience,
Jaap

**Comment by stant** [comment]
For one, please download and read my doc on how to create and use readers. I think it answers some of your questions. If you were using the original importer that had the built in ING, that works differently than the multiple versions newer one now.

1.) yes, you can import the same file more than once, BUT BUT importer skips duplicates. It tells you how many is SKIPPED after the import. So, if you import the same 20 item file twice, it will import 20 the first time and 0 the second time. Yes, if you delete them from MD you can import them again. Duplicates are bad.

The Basics of how my Importer Works:

It does want you to validate a csv file before you can import it.  
That is why when you pick a file first, it displays "Find Reader". It means Find one that works.

There are 2 ways to validate a file:
1.) pick a file. then hit "Find Reader(s) that Work on Import File"
        This tests all the readers and gives you a "File Reader:" list of ones that work for your file.
2.) hit "Preview Import". This also validates your file against the Reader you chose and tells you how it parsed the file and whether it will work or not.

If either of these 2 works, the "Process" button will be enabled.

> >  I would prefer that if you have 1 reader the importer would automatically use that reader.

I deleted down to one reader and it automatically put that in my File Reader list. You still have to validate your file though. It will not let you Process an invalid file.

> > BTW: When I click on “Find Import File(s) for this reader, when a file is already selected, I get the message “Unsupported CSV file format.”, which is a misleading remark.

I do not get this. You would have to give me exact steps and a file.

2.) Yes, talk to MD about blue ball. My importer turns them on.

3.) credit or debit. I explain in my doc/manual. Just flip -Payment- to/from -Deposit-

So far, I have not seen 'issues', you just have to learn how to use the newer version of the importer it looks like.

The way I use it now is I set up the "Filename Matcher:" for each reader.
Then when I download a new file I do:

pick my "File Reader" like say Discover
hit "Find Import File(s) for this Reader"
it matches my file 'name' and fills in the "Select Import File" drop down.
then I hit "Preview Import" to validate and show my parsed file.
then hit "Process"

American Express I use: "Filename Matcher:"  (Transactions|amex)_.(csv|CSV)
Discover I use:  "Filename Matcher:"  DFS-._.(csv|CSV)
myVisa:  "Filename Matcher:"  Transactions_Download.csv     (they always use the same filename)
