### ISSUE TITLE
main window layout is too big

### ISSUE THREAD

**Issue by sreilly** [stant/mdcsvimporter2015#3]
The main import window doesn't fit in the default window on the mac.  An example is here:
 https://www.dropbox.com/s/fiuriclny4izadx/Screenshot%202015-04-14%2008.13.14.png?dl=0

**Comment by stant** [comment]
Hmm. That's one thing I don't like about the new MD2015 gui is that it is bigger too. It shows less on a screen than does MD2014. To try to make up for screen diff.s is one reason I did v19. It lets users save the importer windows at whatever size and location they last sized them to.

I see in my linux it might be about 900x500 and around 800x500 or so in windows 7. 

So, for your problem, are you saying my windows are too big even at full screen? are you using a 13" Mac? then I have a problem. i know the config screen is even bigger.

Do you have a suggested way to handle this with Swing? What do people do? 
scale the whole window?
reset the font to something smaller?
Do you set gui defaults per OS or what?

Thanks,
Stan

**Comment by sreilly** [comment]
I don't think this is related to the updated design of MD2015, which does have a bit more whitespace, but mostly only on the sidebar in a little in the register.

I'm on a 15" MBP with a resolution of 1920x1200.  My main concern is that the layout is a bit confusing and some things don't fit at the default window size.  The problem is likely because the layout has fixed sizes that don't work across different platforms and fonts.  I'm also unable to edit the layout form using IDEA.  Would you mind if I just changed it so that the layout happens in code instead of in the separate layout file?  I have some shortcuts that make it a lot easier and also readable to have the layout in code.

When I run from the extensions menu there are no items in the File..., Select Im..., and Dat... popups.  I've attached a signed version of the extension that shows this.... hopefully it comes through.

Thanks,
Sean

**Comment by stant** [comment]
Hi. I'm not saying md2015 ui is the whole problem, but I just measured on my 1600x900 screen. At full screen I see in 
md2014:  Left side: 32 lines                               Register: 18.75 lines
md2015:  Left side: 24 lines (25% less shown)  Register: 14.75 lines (21% less shown)
That's a pretty big diff.

So if you have that kind of resolution, that is not the problem. It is just the default startup size as you say, right? If the user makes their windows bigger they are fine after that as my v19 changes remember what they used last time. 

So, I like designing a gui screen with a gui screen as I can do in netbeans. Isn't it a pain if you want to move things around on the screen to do it in a text code file? Does IDEA have a gui editor?
Without changing from netbeans, do you know what I can do differently for the layout design to make it calculate a better startup screen size? Isn't screen.pack() supposed to do that for me? I can see if I can make the layout not set a default size and let .pack() do it if I am not already. Maybe some predefined size is overriding .pack()?

> > When I run from the extensions menu there are no items in the File..., Select Im..., and Dat... popups.  I've attached a signed version of the extension that shows this.... hopefully it comes through.

Your attachment did not come through.
I know there is personal preference on screen layout. I try to make it make sense. The date field is not really set on this screen but just shows you what got picked. The other fields you say start out blank are meant to start out blank. I did write the doc with screen shots on how to use my importer. There are 2 ways to start out. You either pick a 'csv File' first and then a 'Reader', or you pick a 'Reader' first and then your 'File'.

Then there are convenience buttons.
If you pick a File, you can hit a button and it will 'Find a reader that works for your file'.
of if you pick a Reader, then you can hit a button to give you a list of files for that reader matching by name.

I started picking my Reader first and hit the button to have it give me a file list and thought this the fastest way to go lately so I flipped Reader above the File picker.

**Comment by sreilly** [comment]
ok, I think I understand what I was doing wrong in my pull-request comment (which I really should have put here instead of on the PR).  Personally I think that it'd be best to let the user choose a file (or files) first and then show the UI to choose the parameters for the import process.  Otherwise it's just not intuitive enough since people need to click a button in the middle of the window to start the process.  It took me such a long time to figure that out :)

I'd be happy to do the work to change it if you like, but it would mean switching to doing the layout in code instead of in netbeans.  I think I can make this quite an easy process as we do all of the Moneydance layout in code using some utilities that are accessible to extensions.  I think that in general doing layout in code is easier because it's a lot less back-and-forth between a separate UI builder and java code.  We can stay in java-land for the whole process :)

Are you ok with me doing that?

Thanks!
Sean

**Comment by stant** [comment]
Hi Sean. 
On the IDE question, I like using the Netbeans IDE so I can pretty easily see the screen I am designing so I would not want to lose that.

This is a top down window process. I might look at getting rid of 'Date Format', but when I have time. I don't get paid so...
You have to define a reader first of all and tell it how to match filenames. An improvement I plan to make is to tell people if they do not have one and that they need to create one first.

1.) So, what I do is download a new trans list csv file from my bank (XYZ)
2.) in MD do, "Import File" (my extension)
3.) I have say 6 defined so I pick the "File Reader" for my bank (XYZ).
4.) I hit button "Find Import File(s) for this Reader."
It populates "Select Import File:" dropdown with my list of files that match my reader "filename matcher". It also gives the number of files that match. Hopefully 1. If not I pick the file I want to import.
5.) Hit "Preview Import" so it validates the importing transactions.
6.) "Process" button becomes enabled. I hit it.
Done.

What button did you think you had to hit in the middle to make it work?
I will try to make it more intuitive when I have time. I'm not sure what you think you would like to change?
