### ISSUE TITLE
Parsing priority

### ISSUE THREAD

**Issue by breaghva** [stant/mdcsvimporter2015#7]
Hi all,
Nice tool, thanks.  Ithink I've found an issue importing text fields which contain a "," character - this is used a lot in some currency values.  The record below:

13/01/2018,"Reference: xxx"," 7.59","WS CALAIS","8,25 EUR COMM.FEE 0.22 Process Date 13/01/2018 Currency Conversion Rate 1.1194 Commission Amount 0.22",

Imports as: 
13/01/2018
Reference: xxx
7.59
WS CALAIS
8

(last field should be:
8,25 EUR COMM.FEE 0.22 Process Date 13/01/2018 Currency Conversion Rate 1.1194 Commission Amount 0.22

I guess the parsing should look for the closing quote character before examining the text for more delimiters...
If there is a workaround, please let me know.

**Comment by stant** [comment]
Hi.This works. Look at the settings I used. I just set: header, footer, Date and fields.
I'm sorry I did not see this among other emails.
![settings](https://user-images.githubusercontent.com/1928413/38836968-dd6e5138-4195-11e8-8c21-b4ff530e8522.jpg)
![entry](https://user-images.githubusercontent.com/1928413/38836969-dd813e74-4195-11e8-8b22-02b328b63101.jpg)
![main](https://user-images.githubusercontent.com/1928413/38836970-dd8fe6cc-4195-11e8-8c4a-a71b42002069.jpg)
![preview](https://user-images.githubusercontent.com/1928413/38836971-dda0ea58-4195-11e8-94e9-685e849f79a6.jpg)
