### ISSUE TITLE
V.21 'Can Be Blank' setting not saved.

### ISSUE THREAD

**Issue by Kevin-N749** [stant/mdcsvimporter2015#8]
Hi Stan,

MD 2017.7.2 (1672)
Windows 10 Home 64-bit
CSV Importer V.21

When setting the parameters for a custom reader, the option 'Can Be Blank' is not saved between closing and reopening the extension.

I was able to confirm the above by reverting back to V.20.

Thank you for your attention to this matter.

-Kevin N.

**Comment by stant** [comment]
I fixed this in v22
