### ISSUE TITLE
Need Regex help

### ISSUE THREAD

**Issue by ae8u** [stant/mdcsvimporter2015#9]
I am trying to import csv files from my bank. The problem is the csv file shows negative values (expenses) with one minus sign and positive values (income) with two minus signs. When they are imported they all come in as expenses. Here is an example of my csv:
posted,,12/31/2018,,INTEREST PAID,Interest,--0.03 
posted,,11/30/2018,,INTEREST PAID,Interest,--0.03 
posted,,10/31/2018,,INTEREST PAID,Interest,--0.03 
posted,,09/28/2018,,INTEREST PAID,Interest,--0.03 
posted,,08/31/2018,,INTEREST PAID,Interest,--0.03 
posted,,07/31/2018,,INTEREST PAID,Interest,--0.05 
posted,,07/23/2018,,USAA FUNDS TRANSFER DB,Transfers,-200 
posted,,07/03/2018,,USAA FUNDS TRANSFER DB,Transfers,-1000
How do I convert the values with a double minus to income? I am guessing that there is a Regex that I can use, but that is beyond my ability. Can you help?

**Comment by stant** [comment]
"?(?:--){0,1}(?<value>.*?)"?(?:[,]|\Z)(?<rest>(.*|\Z))
regex are hard. I am sorry, I did not see any email for issues.
it looks like adding (?:--){0,1}   in above takes out any -- which will make it positive.
so "15" -> "15"      "-15" -> "-15"    "--15" -> "15"
i found this regex tester that is helpful!
![db-minus](https://user-images.githubusercontent.com/1928413/57586096-887f9800-74a5-11e9-93c9-4f63156d259e.png)

**Comment by stant** [comment]
I was not getting emails for issues. I now figured out how to turn that on. Hope that regex site helped.
